# Generated by Django 2.2.4 on 2019-09-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_photo', to='blogapps.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, default='author.jpg', null=True, upload_to='pics'),
        ),
    ]
