# Generated by Django 2.2.4 on 2019-09-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0002_auto_20190925_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author_image',
        ),
    ]
