# Generated by Django 2.2.4 on 2019-09-27 06:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0003_remove_blogs_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
