# Generated by Django 2.2.4 on 2019-09-27 06:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0004_auto_20190927_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=tinymce.models.HTMLField(verbose_name=''),
        ),
    ]
