# Generated by Django 2.2.4 on 2019-09-28 06:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0005_auto_20190927_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
                ('message', tinymce.models.HTMLField(verbose_name='Message')),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
