# Generated by Django 2.2.4 on 2019-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0007_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
