# Generated by Django 2.2.4 on 2019-10-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0009_auto_20190928_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='author.jpg', upload_to='pics'),
        ),
    ]
