# Generated by Django 2.2.4 on 2019-10-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0010_auto_20191001_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='pics/author.jpg', upload_to='pics'),
        ),
    ]
