# Generated by Django 2.2.4 on 2019-10-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0015_auto_20191001_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
