# Generated by Django 2.2.4 on 2019-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0019_auto_20191002_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, default='pics/author.jpg', upload_to='media/pics/'),
        ),
    ]
