# Generated by Django 2.2.4 on 2019-10-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0021_auto_20191002_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
