# Generated by Django 2.2.4 on 2019-10-12 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0022_delete_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('image', models.ImageField(default='pics/author.jpg', upload_to='pics/')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapps.Author')),
            ],
        ),
    ]
