# Generated by Django 2.2.4 on 2019-09-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=None)),
                ('offer', models.BooleanField(default=False)),
                ('image', models.ImageField(default=None, upload_to='pics')),
            ],
        ),
    ]
