# Generated by Django 2.2.4 on 2019-09-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
