# Generated by Django 2.2.4 on 2019-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0002_auto_20190913_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textile',
            name='image',
            field=models.ImageField(blank=True, default='sample.jpg', upload_to='pics'),
            preserve_default=False,
        ),
    ]
