# Generated by Django 2.2.4 on 2019-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0003_auto_20190913_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textile',
            name='image',
            field=models.ImageField(blank=True, default='author.jpg', upload_to='pics'),
        ),
    ]
