# Generated by Django 2.2.4 on 2019-10-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0006_auto_20191010_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
