# Generated by Django 2.2.4 on 2019-10-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0007_auto_20191014_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=None),
        ),
    ]
