# Generated by Django 2.2.4 on 2019-10-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0009_auto_20191014_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
